// Which tutorial steps have a real recording, and where it lives.
//
// GENERATED by scripts/voice/ingest-narration.sh. Do not hand-edit — the next
// ingest overwrites it.
//
// Why a generated set rather than audioUrl written into all 51 steps of
// script.ts: the recordings arrive in batches and get re-recorded individually,
// and 51 hand-maintained string literals would drift from the files on disk the
// first time one was re-cut. The list is derived from what actually exists in
// public/tutorial-audio, so it cannot claim a recording that is not there.
//
// An explicit `audioUrl` on a step still wins — see resolveAudio below — so a
// one-off recording can be pointed anywhere without touching this file.

/** Step ids that have an mp3 in public/tutorial-audio. */
export const RECORDED_STEPS: ReadonlySet<string> = new Set<string>([
  // none yet — the browser voice reads every step until the first ingest.
]);

/**
 * The audio for a step, or null to fall back to the browser voice.
 *
 * `narrate()` already treats null as "speak it", so a step with no recording
 * behaves exactly as it did before any of this existed.
 */
export function resolveAudio(step: { id: string; audioUrl?: string | null }): string | null {
  if (step.audioUrl) return step.audioUrl;
  return RECORDED_STEPS.has(step.id) ? `/tutorial-audio/${step.id}.mp3` : null;
}
