/**
 * Emit the SQL that seeds the shared meal + recipe library.
 *
 * Why a generator rather than a hand-written .sql file: the macros in the SQL
 * must be the SAME numbers the app's tests check. Writing the SQL by hand would
 * create a second copy that drifts the first time somebody edits a recipe, and
 * the drift would be invisible — the tests would still pass against the TS
 * while the database served something else.
 *
 * Run:  npx tsx scripts/emit-library-seed.ts > /tmp/library.sql
 *
 * The seed is IDEMPOTENT. It deletes the previous library rows (the ones with a
 * null client_id / the library marker) and re-inserts, so re-running it after an
 * edit updates the library rather than duplicating it. It never touches a row
 * belonging to a client.
 */

import { MEAL_LIBRARY, mealTotals } from "../src/lib/nutrition/mealLibrary";
import { RECIPE_LIBRARY, perServing } from "../src/lib/nutrition/recipeLibrary";

const q = (s: string) => "'" + s.replace(/'/g, "''") + "'";
const arr = (xs: string[]) => "ARRAY[" + xs.map(q).join(",") + "]::text[]";

const out: string[] = [];
out.push("-- Generated by scripts/emit-library-seed.ts — DO NOT EDIT BY HAND.");
out.push("-- Source of truth: src/lib/nutrition/mealLibrary.ts + recipeLibrary.ts");
out.push("begin;");

// ── Meals ────────────────────────────────────────────────────────────────
// Library meals live in my_meals with a NULL client_id. Only these are removed;
// a row with a client_id belongs to a person and is never touched here.
out.push("delete from public.my_meals where client_id is null;");

for (const m of MEAL_LIBRARY) {
  const t = mealTotals(m.items);
  const items = m.items.map((i) => ({
    n: i.n, a: i.a, p: i.p, c: i.c, f: i.f,
    k: Math.round((4 * i.p + 4 * i.c + 9 * i.f) * 10) / 10,
    fac: 1,
  }));
  const totals = { kcal: t.kcal, protein: t.protein, carbs: t.carbs, fats: t.fats };
  out.push(
    `insert into public.my_meals (client_id, name, items, totals) values ` +
      `(null, ${q(m.name)}, ${q(JSON.stringify(items))}::jsonb, ${q(JSON.stringify({ ...totals, slot: m.slot, tags: m.tags }))}::jsonb);`
  );
}

// ── Recipes ──────────────────────────────────────────────────────────────
// Library recipes are client_id null + visibility 'public'. RLS already lets
// everybody read public recipes and their ingredients, so no policy is needed.
out.push("delete from public.recipe_ingredients where recipe_id in (select id from public.recipes where client_id is null);");
out.push("delete from public.recipes where client_id is null;");

for (const r of RECIPE_LIBRARY) {
  const ps = perServing(r);
  out.push(
    `with r as (insert into public.recipes ` +
      `(client_id, title, description, servings, prep_minutes, cook_minutes, instructions, tags, visibility, ` +
      `total_kcal, total_protein, total_carbs, total_fats) values (` +
      `null, ${q(r.title)}, ${q(r.description)}, ${r.servings}, ${r.prepMinutes}, ${r.cookMinutes}, ` +
      `${arr(r.instructions)}, ${arr(r.tags)}, 'public', ` +
      `${ps.kcal}, ${ps.protein}, ${ps.carbs}, ${ps.fats}) returning id)` +
      `\ninsert into public.recipe_ingredients (recipe_id, position, food, amount, unit, protein, carbs, fats, source) values ` +
      r.ingredients
        .map((i, idx) => {
          // Split "24 oz (680 g) raw" into a number and everything after it, so
          // the amount column is numeric and the unit keeps the human wording.
          const m = i.a.match(/^([\d.]+)\s*(.*)$/);
          const amount = m ? m[1] : "null";
          const unit = m ? m[2] : i.a;
          return `((select id from r), ${idx + 1}, ${q(i.n)}, ${amount}, ${q(unit)}, ${i.p}, ${i.c}, ${i.f}, 'manual')`;
        })
        .join(",\n  ") +
      ";"
  );
}

out.push("commit;");
console.log(out.join("\n"));
