name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_tvOt9zO3LMPE2khGKlZsWJmcRRVA/gun0ydyAB0
